### Torch.Autograd

Neural Network는 input data에 대해서 일정하게 짜여진 함수들의 집합이다. 신경망의 학습은 2개의 순서를 번갈아가며 진행된다.
1. Forward Propagation
    - forward propropagation에서는 신경망이 최대한 예상되는 결과와 비슷한 값을 계산하도록 한다. 주어진 데이터를 몇가지의 함수를 거쳐서 해당 값을 도출해내는 과정이다
2. Backward Propagation
    - backward propagation에서는 신경망이 forward에서 계산한 값과 실제 값과의 에러를 통하여 forward 과정에 관여하는 함수들의 coefficient를 조정하게 된다. 해당 에러를 줄이기 위해서 시도하는 방법이 gradient descent이다.
   

In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights

In [2]:
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1,3, 64, 64)
labels = torch.rand(1, 1000)
data

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/bengal/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
52.5%IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

100.0%


tensor([[[[0.2924, 0.7940, 0.6754,  ..., 0.2285, 0.3524, 0.6434],
          [0.3129, 0.6036, 0.6014,  ..., 0.0313, 0.5214, 0.6913],
          [0.7746, 0.4357, 0.4249,  ..., 0.2607, 0.3370, 0.2786],
          ...,
          [0.6995, 0.6524, 0.8202,  ..., 0.3089, 0.6650, 0.9281],
          [0.8918, 0.9109, 0.3667,  ..., 0.1372, 0.1143, 0.9359],
          [0.4295, 0.4827, 0.1603,  ..., 0.2958, 0.9389, 0.3204]],

         [[0.2747, 0.8388, 0.2617,  ..., 0.1469, 0.3418, 0.8198],
          [0.2818, 0.5565, 0.2686,  ..., 0.7947, 0.7478, 0.6269],
          [0.6801, 0.2062, 0.3947,  ..., 0.7138, 0.7213, 0.7986],
          ...,
          [0.2987, 0.3852, 0.6849,  ..., 0.1673, 0.0211, 0.5106],
          [0.9239, 0.3547, 0.5554,  ..., 0.1668, 0.3100, 0.0916],
          [0.4431, 0.2837, 0.6451,  ..., 0.5512, 0.4580, 0.0717]],

         [[0.6931, 0.6863, 0.2628,  ..., 0.5450, 0.9183, 0.3732],
          [0.8348, 0.8503, 0.9560,  ..., 0.3824, 0.0155, 0.0859],
          [0.8740, 0.8421, 0.1673,  ..., 0

In [4]:
prediction = model(data)
prediction

tensor([[-6.7616e-01, -4.8367e-01, -9.4357e-01, -1.9005e+00, -7.6212e-01,
         -1.6590e-01, -7.0727e-01,  5.0403e-01,  4.1408e-01, -7.3312e-01,
         -8.5949e-01, -8.2986e-01, -2.2684e-01, -1.1730e+00, -1.1259e+00,
         -6.8169e-01, -9.5191e-01, -1.9915e-01, -8.1600e-01, -6.8198e-01,
         -1.5927e+00, -5.5896e-01, -1.4093e+00,  7.6598e-02, -9.5115e-01,
         -1.0107e+00, -6.6025e-01, -9.8165e-01, -5.8704e-01, -5.1272e-01,
         -9.8411e-01, -7.6213e-01, -2.6682e-01, -6.8752e-01, -2.6551e-01,
         -4.8228e-01,  3.4216e-01, -8.4923e-01, -3.0404e-01, -3.1955e-01,
         -5.7145e-01, -8.6783e-01, -8.3467e-01, -3.4314e-01, -3.4298e-01,
         -3.3317e-01, -6.8708e-01, -4.0579e-01, -1.3077e+00, -1.0545e+00,
         -4.3926e-01,  7.0462e-01,  2.5921e-02, -4.5851e-01,  1.0827e-02,
         -1.1631e+00, -6.0965e-02, -1.4908e+00, -3.9239e-01, -3.6689e-01,
          1.0438e+00,  3.0931e-01, -1.2758e-02,  2.3050e-01, -7.7826e-01,
         -1.7899e-01, -1.7452e-01, -4.

In [5]:
loss = (prediction - labels).sum()
loss.backward()


In [6]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)
optim.step()

In [7]:
prediction = model(data)
prediction

tensor([[-4.9396, -4.7527, -5.2660, -5.9451, -5.0284, -4.4448, -4.8707, -4.2759,
         -4.2463, -5.1580, -5.1449, -5.2094, -4.6483, -5.5804, -5.5768, -5.1379,
         -5.3703, -4.8332, -5.3484, -5.0630, -6.0255, -5.0689, -6.0435, -4.5516,
         -5.5525, -5.5676, -5.0044, -5.4073, -5.1635, -4.6740, -5.3985, -5.2049,
         -4.6732, -5.0520, -4.6593, -4.8895, -3.9059, -5.2523, -4.6104, -4.7216,
         -5.0065, -5.2291, -5.2640, -4.7012, -4.8448, -4.7119, -5.1012, -4.6948,
         -5.6049, -5.2094, -4.8185, -3.7923, -4.4058, -4.8650, -4.4284, -5.5853,
         -4.4636, -5.9353, -4.7372, -4.7783, -3.3812, -4.1506, -4.3100, -4.0504,
         -5.0791, -4.6756, -4.5496, -4.7171, -5.0679, -5.5834, -5.8068, -3.9558,
         -5.8583, -4.6111, -5.5554, -5.5842, -4.2847, -5.0702, -3.9617, -4.0602,
         -5.2033, -6.2966, -4.5768, -5.1307, -4.9534, -4.4251, -4.1511, -4.0793,
         -4.3957, -5.1750, -5.2151, -5.8676, -6.2006, -5.2434, -4.6254, -6.3825,
         -4.9848, -4.7375, -

In [8]:
prediction.shape

torch.Size([1, 1000])