In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [7]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [8]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.1378, 0.5413],
        [0.4013, 0.0580]])

In [10]:
shape = (3, 4)

rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.4096, 0.0055, 0.8532, 0.4470],
        [0.9545, 0.2710, 0.5969, 0.9256],
        [0.9954, 0.3240, 0.0257, 0.4634]])

In [18]:
tensor = torch.ones((4,4,3))
tensor[2:, 1:3, 1:] = 0
tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 0., 0.],
         [1., 0., 0.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 0., 0.],
         [1., 0., 0.],
         [1., 1., 1.]]])

In [19]:
shape = (3,3)
ran1 = torch.rand(shape)
ran2 = torch.rand(shape)
ran3 = torch.rand(shape)

torch.stack([ran1, ran2, ran3])

tensor([[[0.5008, 0.8233, 0.4533],
         [0.8107, 0.7287, 0.2984],
         [0.3614, 0.2941, 0.4944]],

        [[0.3214, 0.1175, 0.8728],
         [0.1253, 0.1316, 0.2517],
         [0.6860, 0.1937, 0.8081]],

        [[0.7404, 0.4665, 0.3880],
         [0.8124, 0.5077, 0.4865],
         [0.1565, 0.3470, 0.8765]]])

In [22]:
torch.cat([ran1, ran2, ran3], axis=-1)

tensor([[0.5008, 0.8233, 0.4533, 0.3214, 0.1175, 0.8728, 0.7404, 0.4665, 0.3880],
        [0.8107, 0.7287, 0.2984, 0.1253, 0.1316, 0.2517, 0.8124, 0.5077, 0.4865],
        [0.3614, 0.2941, 0.4944, 0.6860, 0.1937, 0.8081, 0.1565, 0.3470, 0.8765]])

In [23]:
torch.cat([ran1, ran2, ran3])

tensor([[0.5008, 0.8233, 0.4533],
        [0.8107, 0.7287, 0.2984],
        [0.3614, 0.2941, 0.4944],
        [0.3214, 0.1175, 0.8728],
        [0.1253, 0.1316, 0.2517],
        [0.6860, 0.1937, 0.8081],
        [0.7404, 0.4665, 0.3880],
        [0.8124, 0.5077, 0.4865],
        [0.1565, 0.3470, 0.8765]])